In [1]:
import os

In [2]:
os.chdir("..")

In [3]:
%pwd

'/Users/beamaia/Documents/ndb_ufes_data_organizer'

In [4]:
import pathlib as pl
import pandas as pd

In [5]:
LINKS_PATH = "data/ndb_ufes/link/images"

In [6]:
images_linked = [int(file.name[7:11]) for file in pl.Path(LINKS_PATH).iterdir()]

In [7]:
images_linked = sorted(images_linked)

In [8]:
max_id = max(images_linked)
min_id = min(images_linked)
range_ids = set(range(min_id, max_id + 1))

In [9]:
missing_ids = list(range_ids - set(images_linked))

In [10]:
ids_df = pd.DataFrame({
        "missing_patch_id": sorted(missing_ids)
    })

In [11]:
ids_df

     missing_patch_id
0                   3
1                  10
2                  12
3                  38
4                  39
..                ...
556              3691
557              3692
558              3726
559              3743
560              3761

[561 rows x 1 columns]

In [12]:
ids_df["origin"] = -1

In [13]:
ids_df

     missing_patch_id  origin
0                   3      -1
1                  10      -1
2                  12      -1
3                  38      -1
4                  39      -1
..                ...     ...
556              3691      -1
557              3692      -1
558              3726      -1
559              3743      -1
560              3761      -1

[561 rows x 2 columns]

In [14]:
ids_df.to_csv("missing_ids.csv", index=False)

In [15]:
print(sorted(missing_ids))

[3, 10, 12, 38, 39, 40, 41, 57, 126, 127, 128, 129, 130, 131, 132, 133, 158, 159, 160, 161, 162, 163, 164, 313, 314, 315, 316, 317, 318, 319, 320, 432, 433, 434, 435, 436, 437, 438, 439, 554, 571, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 713, 714, 715, 716, 717, 718, 719, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 871, 875, 877, 878, 879, 880, 881, 882, 883, 884, 885, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 997, 998, 999, 1000, 1001, 1002, 1017, 1018, 1162, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1287, 1378, 1379, 1380, 1381, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1453, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1502, 1504, 1505, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1569, 1575, 1576, 1577, 1578, 1597, 1598, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1612, 1687, 1688, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1718, 1719, 1720, 1721, 1724, 1726, 1729, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1815, 1816, 1817, 1818, 1820, 1821, 1822, 1823, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1898, 1899, 1900, 1901, 1905, 1907, 1909, 1912, 1913, 1975, 1977, 2094, 2095, 2096, 2098, 2099, 2101, 2102, 2103, 2104, 2105, 2106, 2107, 2108, 2109, 2110, 2111, 2112, 2113, 2114, 2115, 2116, 2117, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2136, 2137, 2139, 2140, 2141, 2142, 2143, 2144, 2145, 2269, 2271, 2272, 2274, 2275, 2276, 2277, 2278, 2279, 2281, 2283, 2284, 2286, 2287, 2289, 2291, 2304, 2305, 2306, 2308, 2309, 2310, 2311, 2312, 2313, 2314, 2331, 2426, 2428, 2430, 2431, 2432, 2434, 2435, 2436, 2438, 2439, 2440, 2441, 2442, 2500, 2501, 2502, 2503, 2504, 2505, 2506, 2507, 2508, 2509, 2510, 2511, 2512, 2513, 2514, 2515, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 2523, 2524, 2525, 2526, 2527, 2528, 2529, 2530, 2531, 2532, 2533, 2534, 2535, 2536, 2537, 2538, 2539, 2540, 2541, 2542, 2543, 2544, 2545, 2546, 2547, 2548, 2549, 2550, 2551, 2553, 2554, 2556, 2557, 2762, 2763, 2764, 2765, 2766, 2768, 2769, 2770, 2771, 2772, 2773, 2774, 2775, 2776, 2777, 2778, 2779, 2780, 2781, 2782, 2783, 2784, 2832, 2840, 2842, 2843, 2844, 2845, 2846, 2847, 2848, 2871, 2872, 2888, 2891, 2899, 2900, 2901, 2908, 2916, 2924, 2965, 2966, 2979, 2980, 2981, 2994, 2995, 2998, 2999, 3005, 3010, 3011, 3012, 3016, 3020, 3021, 3030, 3033, 3037, 3038, 3063, 3064, 3065, 3077, 3079, 3096, 3103, 3104, 3124, 3125, 3126, 3137, 3138, 3142, 3147, 3148, 3161, 3162, 3186, 3187, 3216, 3217, 3242, 3259, 3260, 3261, 3262, 3282, 3289, 3307, 3308, 3311, 3312, 3383, 3384, 3385, 3386, 3388, 3406, 3407, 3422, 3425, 3427, 3445, 3446, 3447, 3448, 3449, 3461, 3462, 3463, 3464, 3465, 3472, 3473, 3474, 3475, 3476, 3490, 3497, 3498, 3520, 3546, 3547, 3548, 3552, 3553, 3554, 3575, 3576, 3577, 3578, 3579, 3580, 3583, 3606, 3622, 3623, 3624, 3625, 3627, 3628, 3674, 3675, 3676, 3677, 3678, 3679, 3680, 3681, 3691, 3692, 3726, 3743, 3761]

In [16]:
for num in sorted(missing_ids):
    print(num, end=" ")

3 10 12 38 39 40 41 57 126 127 128 129 130 131 132 133 158 159 160 161 162 163 164 313 314 315 316 317 318 319 320 432 433 434 435 436 437 438 439 554 571 638 639 640 641 642 643 644 645 646 647 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665 666 667 668 713 714 715 716 717 718 719 785 786 787 788 789 790 791 792 793 794 871 875 877 878 879 880 881 882 883 884 885 892 893 894 895 896 897 898 899 900 901 902 903 904 905 906 997 998 999 1000 1001 1002 1017 1018 1162 1265 1266 1267 1268 1269 1270 1271 1272 1273 1274 1275 1276 1277 1278 1279 1280 1281 1282 1283 1284 1285 1287 1378 1379 1380 1381 1382 1383 1384 1385 1386 1387 1388 1453 1456 1457 1458 1459 1460 1461 1462 1463 1464 1469 1470 1471 1472 1473 1474 1475 1476 1477 1478 1502 1504 1505 1507 1508 1509 1510 1511 1512 1513 1569 1575 1576 1577 1578 1597 1598 1600 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610 1611 1612 1687 1688 1690 1691 1692 1693 1694 1695 1696 1697 1698 1699 1700 1701 1702 1703 1704 1718 1719 1720 1721 1724 1726 1729 1731 1732 1733 1734 1735 1736 1737 1738 1739 1815 1816 1817 1818 1820 1821 1822 1823 1854 1855 1856 1857 1858 1859 1860 1861 1862 1863 1864 1865 1898 1899 1900 1901 1905 1907 1909 1912 1913 1975 1977 2094 2095 2096 2098 2099 2101 2102 2103 2104 2105 2106 2107 2108 2109 2110 2111 2112 2113 2114 2115 2116 2117 2129 2130 2131 2132 2133 2134 2135 2136 2137 2139 2140 2141 2142 2143 2144 2145 2269 2271 2272 2274 2275 2276 2277 2278 2279 2281 2283 2284 2286 2287 2289 2291 2304 2305 2306 2308 2309 2310 2311 2312 2313 2314 2331 2426 2428 2430 2431 2432 2434 2435 2436 2438 2439 2440 2441 2442 2500 2501 2502 2503 2504 2505 2506 2507 2508 2509 2510 2511 2512 2513 2514 2515 2516 2517 2518 2519 2520 2521 2522 2523 2524 2525 2526 2527 2528 2529 2530 2531 2532 2533 2534 2535 2536 2537 2538 2539 2540 2541 2542 2543 2544 2545 2546 2547 2548 2549 2550 2551 2553 2554 2556 2557 2762 2763 2764 2765 2766 2768 2769 2770 2771 2772 2773 2774 2775 2776 2777 2778 2779 2780 2781 2782 2783 2784 2832 2840 2842 2843 2844 2845 2846 2847 2848 2871 2872 2888 2891 2899 2900 2901 2908 2916 2924 2965 2966 2979 2980 2981 2994 2995 2998 2999 3005 3010 3011 3012 3016 3020 3021 3030 3033 3037 3038 3063 3064 3065 3077 3079 3096 3103 3104 3124 3125 3126 3137 3138 3142 3147 3148 3161 3162 3186 3187 3216 3217 3242 3259 3260 3261 3262 3282 3289 3307 3308 3311 3312 3383 3384 3385 3386 3388 3406 3407 3422 3425 3427 3445 3446 3447 3448 3449 3461 3462 3463 3464 3465 3472 3473 3474 3475 3476 3490 3497 3498 3520 3546 3547 3548 3552 3553 3554 3575 3576 3577 3578 3579 3580 3583 3606 3622 3623 3624 3625 3627 3628 3674 3675 3676 3677 3678 3679 3680 3681 3691 3692 3726 3743 3761