In [1]:
import os
os.chdir("..")
%pwd

'/Users/beamaia/Documents/ndb_ufes_data_organizer'

In [2]:
import pathlib as pl

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import cv2 as cv

## Get ids

In [3]:
missing_ids = pd.read_csv("missing_ids.csv")
wrong_ids = pd.read_csv("wrong_ids.csv")

In [4]:
missing_ids.head()

   missing_patch_id  origin
0                 3      -1
1                10      -1
2                12      -1
3                38      -1
4                39      -1

In [5]:
wrong_ids.head()

   patch  correct_origin
0  p0011            -1.0
1  p0227            18.0
2  p0230            18.0
3  p0281           156.0
4  p0285           156.0

In [6]:
unknown_origin_wrong_ids = wrong_ids[wrong_ids["correct_origin"] == -1]

In [7]:
unknown_origin_wrong_ids.head()

    patch  correct_origin
0   p0011            -1.0
20  p0870            -1.0
21  P0872            -1.0
22  p0873            -1.0
23  p0874            -1.0

In [8]:
len(unknown_origin_wrong_ids)

113

In [9]:
len(missing_ids)

561

In [10]:
missing_ids["patch"] = missing_ids["missing_patch_id"].apply(lambda x: f"p{x:04}" )

In [11]:
missing_ids = missing_ids.drop(columns=["missing_patch_id"])
unknown_origin_wrong_ids = unknown_origin_wrong_ids.reset_index(drop=True)
unknown_origin_wrong_ids["origin"] = -1
unknown_origin_wrong_ids = unknown_origin_wrong_ids.drop(columns=["correct_origin"])

In [12]:
all_missing_ids = pd.concat([missing_ids, unknown_origin_wrong_ids], axis=0)
all_missing_ids["patch"] = all_missing_ids["patch"].apply(lambda x: x.lower())
all_missing_ids = all_missing_ids.sort_values(by=["patch"])
all_missing_ids = all_missing_ids.reset_index(drop=True)

In [13]:
all_missing_ids.head()

   origin  patch
0      -1  p0003
1      -1  p0010
2      -1  p0011
3      -1  p0012
4      -1  p0038

In [14]:
all_missing_ids

     origin  patch
0        -1  p0003
1        -1  p0010
2        -1  p0011
3        -1  p0012
4        -1  p0038
..      ...    ...
669      -1  p3723
670      -1  p3724
671      -1  p3726
672      -1  p3743
673      -1  p3761

[674 rows x 2 columns]

In [15]:
DATA_PATH = pl.Path("data/ndb_ufes/patch/images")
images_paths = sorted([img.name.split(".")[0] for img in DATA_PATH.glob("*.png")])

In [16]:
for row in all_missing_ids.iterrows():
    patch = row[1]["patch"]

    if patch in images_paths:
        print(f"Patch {patch} is present")
        all_missing_ids.at[row[0], "path"] = DATA_PATH / f"{patch}.png"

Patch p0003 is present
Patch p0010 is present
Patch p0011 is present
Patch p0012 is present
Patch p0038 is present
Patch p0039 is present
Patch p0040 is present
Patch p0041 is present
Patch p0057 is present
Patch p0126 is present
Patch p0127 is present
Patch p0128 is present
Patch p0129 is present
Patch p0130 is present
Patch p0131 is present
Patch p0132 is present
Patch p0133 is present
Patch p0158 is present
Patch p0159 is present
Patch p0160 is present
Patch p0161 is present
Patch p0162 is present
Patch p0163 is present
Patch p0164 is present
Patch p0313 is present
Patch p0314 is present
Patch p0315 is present
Patch p0316 is present
Patch p0317 is present
Patch p0318 is present
Patch p0319 is present
Patch p0320 is present
Patch p0432 is present
Patch p0433 is present
Patch p0434 is present
Patch p0435 is present
Patch p0436 is present
Patch p0437 is present
Patch p0438 is present
Patch p0439 is present
Patch p0554 is present
Patch p0571 is present
Patch p0638 is present
Patch p0639 is present
Patch p0640 is present
Patch p0641 is present
Patch p0642 is present
Patch p0643 is present
Patch p0644 is present
Patch p0645 is present
Patch p0646 is present
Patch p0647 is present
Patch p0648 is present
Patch p0649 is present
Patch p0650 is present
Patch p0651 is present
Patch p0652 is present
Patch p0653 is present
Patch p0654 is present
Patch p0655 is present
Patch p0656 is present
Patch p0657 is present
Patch p0658 is present
Patch p0659 is present
Patch p0660 is present
Patch p0661 is present
Patch p0662 is present
Patch p0663 is present
Patch p0664 is present
Patch p0665 is present
Patch p0666 is present
Patch p0667 is present
Patch p0668 is present
Patch p0713 is present
Patch p0714 is present
Patch p0715 is present
Patch p0716 is present
Patch p0717 is present
Patch p0718 is present
Patch p0719 is present
Patch p0785 is present
Patch p0786 is present
Patch p0787 is present
Patch p0788 is present
Patch p0789 is present
Patch p0790 is present
Patch p0791 is present
Patch p0792 is present
Patch p0793 is present
Patch p0794 is present
Patch p0870 is present
Patch p0871 is present
Patch p0872 is present
Patch p0873 is present
Patch p0874 is present
Patch p0875 is present
Patch p0876 is present
Patch p0877 is present
Patch p0878 is present
Patch p0879 is present
Patch p0880 is present
Patch p0881 is present
Patch p0882 is present
Patch p0883 is present
Patch p0884 is present
Patch p0885 is present
Patch p0892 is present
Patch p0893 is present
Patch p0894 is present
Patch p0895 is present
Patch p0896 is present
Patch p0897 is present
Patch p0898 is present
Patch p0899 is present
Patch p0900 is present
Patch p0901 is present
Patch p0902 is present
Patch p0903 is present
Patch p0904 is present
Patch p0905 is present
Patch p0906 is present
Patch p0946 is present
Patch p0947 is present
Patch p0948 is present
Patch p0966 is present
Patch p0997 is present
Patch p0998 is present
Patch p0999 is present
Patch p1000 is present
Patch p1001 is present
Patch p1002 is present
Patch p1017 is present
Patch p1018 is present
Patch p1078 is present
Patch p1137 is present
Patch p1138 is present
Patch p1139 is present
Patch p1162 is present
Patch p1172 is present
Patch p1173 is present
Patch p1174 is present
Patch p1175 is present
Patch p1192 is present
Patch p1265 is present
Patch p1266 is present
Patch p1267 is present
Patch p1268 is present
Patch p1269 is present
Patch p1270 is present
Patch p1271 is present
Patch p1272 is present
Patch p1273 is present
Patch p1274 is present
Patch p1275 is present
Patch p1276 is present
Patch p1277 is present
Patch p1278 is present
Patch p1279 is present
Patch p1280 is present
Patch p1281 is present
Patch p1282 is present
Patch p1283 is present
Patch p1284 is present
Patch p1285 is present
Patch p1286 is present
Patch p1287 is present
Patch p1324 is present
Patch p1325 is present
Patch p1326 is present
Patch p1378 is present
Patch p1379 is present
Patch p1380 is present
Patch p1381 is present
Patch p1382 is present
Patch p1383 is present
Patch p1384 is present
Patch p1385 is present
Patch p1386 is present
Patch p1387 is present
Patch p1388 is present
Patch p1453 is present
Patch p1456 is present
Patch p1457 is present
Patch p1458 is present
Patch p1459 is present
Patch p1460 is present
Patch p1461 is present
Patch p1462 is present
Patch p1463 is present
Patch p1464 is present
Patch p1465 is present
Patch p1466 is present
Patch p1469 is present
Patch p1470 is present
Patch p1471 is present
Patch p1472 is present
Patch p1473 is present
Patch p1474 is present
Patch p1475 is present
Patch p1476 is present
Patch p1477 is present
Patch p1478 is present
Patch p1502 is present
Patch p1503 is present
Patch p1504 is present
Patch p1505 is present
Patch p1506 is present
Patch p1507 is present
Patch p1508 is present
Patch p1509 is present
Patch p1510 is present
Patch p1511 is present
Patch p1512 is present
Patch p1513 is present
Patch p1562 is present
Patch p1569 is present
Patch p1570 is present
Patch p1574 is present
Patch p1575 is present
Patch p1576 is present
Patch p1577 is present
Patch p1578 is present
Patch p1597 is present
Patch p1598 is present
Patch p1599 is present
Patch p1600 is present
Patch p1601 is present
Patch p1602 is present
Patch p1603 is present
Patch p1604 is present
Patch p1605 is present
Patch p1606 is present
Patch p1607 is present
Patch p1608 is present
Patch p1609 is present
Patch p1610 is present
Patch p1611 is present
Patch p1612 is present
Patch p1687 is present
Patch p1688 is present
Patch p1689 is present
Patch p1690 is present
Patch p1691 is present
Patch p1692 is present
Patch p1693 is present
Patch p1694 is present
Patch p1695 is present
Patch p1696 is present
Patch p1697 is present
Patch p1698 is present
Patch p1699 is present
Patch p1700 is present
Patch p1701 is present
Patch p1702 is present
Patch p1703 is present
Patch p1704 is present
Patch p1718 is present
Patch p1719 is present
Patch p1720 is present
Patch p1721 is present
Patch p1722 is present
Patch p1723 is present
Patch p1724 is present
Patch p1725 is present
Patch p1726 is present
Patch p1727 is present
Patch p1728 is present
Patch p1729 is present
Patch p1730 is present
Patch p1731 is present
Patch p1732 is present
Patch p1733 is present
Patch p1734 is present
Patch p1735 is present
Patch p1736 is present
Patch p1737 is present
Patch p1738 is present
Patch p1739 is present
Patch p1815 is present
Patch p1816 is present
Patch p1817 is present
Patch p1818 is present
Patch p1819 is present
Patch p1820 is present
Patch p1821 is present
Patch p1822 is present
Patch p1823 is present
Patch p1854 is present
Patch p1855 is present
Patch p1856 is present
Patch p1857 is present
Patch p1858 is present
Patch p1859 is present
Patch p1860 is present
Patch p1861 is present
Patch p1862 is present
Patch p1863 is present
Patch p1864 is present
Patch p1865 is present
Patch p1898 is present
Patch p1899 is present
Patch p1900 is present
Patch p1901 is present
Patch p1902 is present
Patch p1903 is present
Patch p1904 is present
Patch p1905 is present
Patch p1906 is present
Patch p1907 is present
Patch p1908 is present
Patch p1909 is present
Patch p1910 is present
Patch p1911 is present
Patch p1912 is present
Patch p1913 is present
Patch p1914 is present
Patch p1915 is present
Patch p1916 is present
Patch p1917 is present
Patch p1958 is present
Patch p1975 is present
Patch p1976 is present
Patch p1977 is present
Patch p1978 is present
Patch p1979 is present
Patch p1980 is present
Patch p2084 is present
Patch p2093 is present
Patch p2094 is present
Patch p2095 is present
Patch p2096 is present
Patch p2097 is present
Patch p2098 is present
Patch p2099 is present
Patch p2100 is present
Patch p2101 is present
Patch p2102 is present
Patch p2103 is present
Patch p2104 is present
Patch p2105 is present
Patch p2106 is present
Patch p2107 is present
Patch p2108 is present
Patch p2109 is present
Patch p2110 is present
Patch p2111 is present
Patch p2112 is present
Patch p2113 is present
Patch p2114 is present
Patch p2115 is present
Patch p2116 is present
Patch p2117 is present
Patch p2129 is present
Patch p2130 is present
Patch p2131 is present
Patch p2132 is present
Patch p2133 is present
Patch p2134 is present
Patch p2135 is present
Patch p2136 is present
Patch p2137 is present
Patch p2138 is present
Patch p2139 is present
Patch p2140 is present
Patch p2141 is present
Patch p2142 is present
Patch p2143 is present
Patch p2144 is present
Patch p2145 is present
Patch p2269 is present
Patch p2270 is present
Patch p2271 is present
Patch p2272 is present
Patch p2273 is present
Patch p2274 is present
Patch p2275 is present
Patch p2276 is present
Patch p2277 is present
Patch p2278 is present
Patch p2279 is present
Patch p2280 is present
Patch p2281 is present
Patch p2282 is present
Patch p2283 is present
Patch p2284 is present
Patch p2285 is present
Patch p2286 is present
Patch p2287 is present
Patch p2288 is present
Patch p2289 is present
Patch p2290 is present
Patch p2291 is present
Patch p2304 is present
Patch p2305 is present
Patch p2306 is present
Patch p2307 is present
Patch p2308 is present
Patch p2309 is present
Patch p2310 is present
Patch p2311 is present
Patch p2312 is present
Patch p2313 is present
Patch p2314 is present
Patch p2331 is present
Patch p2425 is present
Patch p2426 is present
Patch p2427 is present
Patch p2428 is present
Patch p2429 is present
Patch p2430 is present
Patch p2431 is present
Patch p2432 is present
Patch p2433 is present
Patch p2434 is present
Patch p2435 is present
Patch p2436 is present
Patch p2437 is present
Patch p2438 is present
Patch p2439 is present
Patch p2440 is present
Patch p2441 is present
Patch p2442 is present
Patch p2500 is present
Patch p2501 is present
Patch p2502 is present
Patch p2503 is present
Patch p2504 is present
Patch p2505 is present
Patch p2506 is present
Patch p2507 is present
Patch p2508 is present
Patch p2509 is present
Patch p2510 is present
Patch p2511 is present
Patch p2512 is present
Patch p2513 is present
Patch p2514 is present
Patch p2515 is present
Patch p2516 is present
Patch p2517 is present
Patch p2518 is present
Patch p2519 is present
Patch p2520 is present
Patch p2521 is present
Patch p2522 is present
Patch p2523 is present
Patch p2524 is present
Patch p2525 is present
Patch p2526 is present
Patch p2527 is present
Patch p2528 is present
Patch p2529 is present
Patch p2530 is present
Patch p2531 is present
Patch p2532 is present
Patch p2533 is present
Patch p2534 is present
Patch p2535 is present
Patch p2536 is present
Patch p2537 is present
Patch p2538 is present
Patch p2539 is present
Patch p2540 is present
Patch p2541 is present
Patch p2542 is present
Patch p2543 is present
Patch p2544 is present
Patch p2545 is present
Patch p2546 is present
Patch p2547 is present
Patch p2548 is present
Patch p2549 is present
Patch p2550 is present
Patch p2551 is present
Patch p2552 is present
Patch p2553 is present
Patch p2554 is present
Patch p2555 is present
Patch p2556 is present
Patch p2557 is present
Patch p2651 is present
Patch p2762 is present
Patch p2763 is present
Patch p2764 is present
Patch p2765 is present
Patch p2766 is present
Patch p2767 is present
Patch p2768 is present
Patch p2769 is present
Patch p2770 is present
Patch p2771 is present
Patch p2772 is present
Patch p2773 is present
Patch p2774 is present
Patch p2775 is present
Patch p2776 is present
Patch p2777 is present
Patch p2778 is present
Patch p2779 is present
Patch p2780 is present
Patch p2781 is present
Patch p2782 is present
Patch p2783 is present
Patch p2784 is present
Patch p2832 is present
Patch p2840 is present
Patch p2842 is present
Patch p2843 is present
Patch p2844 is present
Patch p2845 is present
Patch p2846 is present
Patch p2847 is present
Patch p2848 is present
Patch p2849 is present
Patch p2871 is present
Patch p2872 is present
Patch p2888 is present
Patch p2891 is present
Patch p2899 is present
Patch p2900 is present
Patch p2901 is present
Patch p2908 is present
Patch p2916 is present
Patch p2924 is present
Patch p2928 is present
Patch p2941 is present
Patch p2942 is present
Patch p2965 is present
Patch p2966 is present
Patch p2979 is present
Patch p2980 is present
Patch p2981 is present
Patch p2994 is present
Patch p2995 is present
Patch p2998 is present
Patch p2999 is present
Patch p3005 is present
Patch p3010 is present
Patch p3011 is present
Patch p3012 is present
Patch p3016 is present
Patch p3019 is present
Patch p3020 is present
Patch p3021 is present
Patch p3030 is present
Patch p3033 is present
Patch p3037 is present
Patch p3038 is present
Patch p3063 is present
Patch p3064 is present
Patch p3065 is present
Patch p3077 is present
Patch p3079 is present
Patch p3095 is present
Patch p3096 is present
Patch p3103 is present
Patch p3104 is present
Patch p3124 is present
Patch p3125 is present
Patch p3126 is present
Patch p3137 is present
Patch p3138 is present
Patch p3142 is present
Patch p3147 is present
Patch p3148 is present
Patch p3161 is present
Patch p3162 is present
Patch p3186 is present
Patch p3187 is present
Patch p3216 is present
Patch p3217 is present
Patch p3242 is present
Patch p3259 is present
Patch p3260 is present
Patch p3261 is present
Patch p3262 is present
Patch p3282 is present
Patch p3289 is present
Patch p3304 is present
Patch p3305 is present
Patch p3306 is present
Patch p3307 is present
Patch p3308 is present
Patch p3311 is present
Patch p3312 is present
Patch p3320 is present
Patch p3338 is present
Patch p3349 is present
Patch p3383 is present
Patch p3384 is present
Patch p3385 is present
Patch p3386 is present
Patch p3387 is present
Patch p3388 is present
Patch p3392 is present
Patch p3393 is present
Patch p3394 is present
Patch p3406 is present
Patch p3407 is present
Patch p3422 is present
Patch p3423 is present
Patch p3424 is present
Patch p3425 is present
Patch p3426 is present
Patch p3427 is present
Patch p3442 is present
Patch p3445 is present
Patch p3446 is present
Patch p3447 is present
Patch p3448 is present
Patch p3449 is present
Patch p3461 is present
Patch p3462 is present
Patch p3463 is present
Patch p3464 is present
Patch p3465 is present
Patch p3472 is present
Patch p3473 is present
Patch p3474 is present
Patch p3475 is present
Patch p3476 is present
Patch p3480 is present
Patch p3490 is present
Patch p3491 is present
Patch p3497 is present
Patch p3498 is present
Patch p3507 is present
Patch p3518 is present
Patch p3519 is present
Patch p3520 is present
Patch p3545 is present
Patch p3546 is present
Patch p3547 is present
Patch p3548 is present
Patch p3552 is present
Patch p3553 is present
Patch p3554 is present
Patch p3575 is present
Patch p3576 is present
Patch p3577 is present
Patch p3578 is present
Patch p3579 is present
Patch p3580 is present
Patch p3583 is present
Patch p3606 is present
Patch p3622 is present
Patch p3623 is present
Patch p3624 is present
Patch p3625 is present
Patch p3626 is present
Patch p3627 is present
Patch p3628 is present
Patch p3629 is present
Patch p3633 is present
Patch p3634 is present
Patch p3650 is present
Patch p3674 is present
Patch p3675 is present
Patch p3676 is present
Patch p3677 is present
Patch p3678 is present
Patch p3679 is present
Patch p3680 is present
Patch p3681 is present
Patch p3691 is present
Patch p3692 is present
Patch p3715 is present
Patch p3720 is present
Patch p3721 is present
Patch p3723 is present
Patch p3724 is present
Patch p3726 is present
Patch p3743 is present
Patch p3761 is present

In [17]:
all_missing_ids.head()

   origin  patch                                  path
0      -1  p0003  data/ndb_ufes/patch/images/p0003.png
1      -1  p0010  data/ndb_ufes/patch/images/p0010.png
2      -1  p0011  data/ndb_ufes/patch/images/p0011.png
3      -1  p0012  data/ndb_ufes/patch/images/p0012.png
4      -1  p0038  data/ndb_ufes/patch/images/p0038.png

In [18]:
# all_missing_ids.to_csv("all_missing_ids.csv", index=False)

In [19]:
len(all_missing_ids)

674

# Algorithm

In [210]:
all_missing_ids = pd.read_csv("all_missing_ids.csv")
all_missing_ids = all_missing_ids[all_missing_ids["origin"] == -1]

In [211]:
LINK_PATH = pl.Path("data/ndb_ufes/link")

In [212]:
indexes = range(0, len(all_missing_ids))

In [213]:
patches_name = all_missing_ids["patch"].values
patches_path = all_missing_ids["path"].values

In [214]:
ORIGIN_PATH = pl.Path("data/ndb_ufes/images")

In [215]:
origin_list = sorted([img.name[:-4] for img in ORIGIN_PATH.iterdir()])
origin_paths = sorted([str(img) for img in ORIGIN_PATH.iterdir()])

In [216]:
len(origin_list)

237

In [217]:
index = 18

In [218]:
possible_origins = dict()

img_rgb_og = cv.imread(origin_paths[index])
img_og = cv.cvtColor(img_rgb_og, cv.IMREAD_GRAYSCALE)

for i, (p_img_name, p_img_path) in enumerate(zip(patches_name, patches_path)):
    img = img_og.copy()
    img_rgb = img_rgb_og.copy()

    p_img_rgb = cv.imread(p_img_path)
    p_img = cv.cvtColor(p_img_rgb, cv.IMREAD_GRAYSCALE)
    pw, ph = p_img.shape[:-1]

    print(f"{i} - Seeing if {p_img_name} is from {origin_list[index]}.")

    method = cv.TM_CCOEFF_NORMED

    res = cv.matchTemplate(img_rgb, p_img_rgb, method)
    min_val, max_val, min_loc, max_loc = cv.minMaxLoc(res)
            
    # loc = np.where(res > 0.4)
            
    # if not len(loc[0]) and not len(loc[1]):
    #     continue
            
    top_left = max_loc
    bottom_right = (top_left[0] + pw, top_left[1] + ph)   
            
    cv.rectangle(img_rgb, top_left, bottom_right, 123, 6)

    plt.subplot(1, 2, 1), plt.imshow(p_img_rgb)
    plt.title(f'Patch Point {p_img_name}'), plt.xticks([]), plt.yticks([])
    plt.subplot(1, 2, 2), plt.imshow(img_rgb)
    plt.title(f'Detected point {origin_list[index]}'), plt.xticks([]), plt.yticks([])
    plt.savefig(LINK_PATH / f"temp/{p_img_name}.png")

    plt.close()

0 - Seeing if p0010 is from 0018.
1 - Seeing if p0011 is from 0018.
2 - Seeing if p0012 is from 0018.
3 - Seeing if p0038 is from 0018.
4 - Seeing if p0039 is from 0018.
5 - Seeing if p0040 is from 0018.
6 - Seeing if p0041 is from 0018.
7 - Seeing if p0057 is from 0018.
8 - Seeing if p0126 is from 0018.
9 - Seeing if p0127 is from 0018.
10 - Seeing if p0128 is from 0018.
11 - Seeing if p0129 is from 0018.
12 - Seeing if p0130 is from 0018.
13 - Seeing if p0131 is from 0018.
14 - Seeing if p0132 is from 0018.
15 - Seeing if p0133 is from 0018.
16 - Seeing if p0158 is from 0018.
17 - Seeing if p0159 is from 0018.
18 - Seeing if p0160 is from 0018.
19 - Seeing if p0161 is from 0018.
20 - Seeing if p0162 is from 0018.
21 - Seeing if p0163 is from 0018.
22 - Seeing if p0164 is from 0018.
23 - Seeing if p0313 is from 0018.
24 - Seeing if p0314 is from 0018.
25 - Seeing if p0315 is from 0018.
26 - Seeing if p0316 is from 0018.
27 - Seeing if p0317 is from 0018.
28 - Seeing if p0318 is from 0018.
29 - Seeing if p0319 is from 0018.
30 - Seeing if p0320 is from 0018.
31 - Seeing if p0432 is from 0018.
32 - Seeing if p0433 is from 0018.
33 - Seeing if p0434 is from 0018.
34 - Seeing if p0435 is from 0018.
35 - Seeing if p0436 is from 0018.
36 - Seeing if p0437 is from 0018.
37 - Seeing if p0438 is from 0018.
38 - Seeing if p0439 is from 0018.
39 - Seeing if p0554 is from 0018.
40 - Seeing if p0571 is from 0018.
41 - Seeing if p0638 is from 0018.
42 - Seeing if p0639 is from 0018.
43 - Seeing if p0640 is from 0018.
44 - Seeing if p0641 is from 0018.
45 - Seeing if p0642 is from 0018.
46 - Seeing if p0643 is from 0018.
47 - Seeing if p0644 is from 0018.
48 - Seeing if p0645 is from 0018.
49 - Seeing if p0646 is from 0018.
50 - Seeing if p0647 is from 0018.
51 - Seeing if p0648 is from 0018.
52 - Seeing if p0649 is from 0018.
53 - Seeing if p0650 is from 0018.
54 - Seeing if p0651 is from 0018.
55 - Seeing if p0652 is from 0018.
56 - Seeing if p0653 is from 0018.
57 - Seeing if p0654 is from 0018.
58 - Seeing if p0655 is from 0018.
59 - Seeing if p0656 is from 0018.
60 - Seeing if p0657 is from 0018.
61 - Seeing if p0658 is from 0018.
62 - Seeing if p0659 is from 0018.
63 - Seeing if p0660 is from 0018.
64 - Seeing if p0661 is from 0018.
65 - Seeing if p0662 is from 0018.
66 - Seeing if p0663 is from 0018.
67 - Seeing if p0664 is from 0018.
68 - Seeing if p0665 is from 0018.
69 - Seeing if p0666 is from 0018.
70 - Seeing if p0667 is from 0018.
71 - Seeing if p0668 is from 0018.
72 - Seeing if p0713 is from 0018.
73 - Seeing if p0714 is from 0018.
74 - Seeing if p0715 is from 0018.
75 - Seeing if p0716 is from 0018.
76 - Seeing if p0717 is from 0018.
77 - Seeing if p0718 is from 0018.
78 - Seeing if p0719 is from 0018.
79 - Seeing if p0785 is from 0018.
80 - Seeing if p0786 is from 0018.
81 - Seeing if p0787 is from 0018.
82 - Seeing if p0788 is from 0018.
83 - Seeing if p0789 is from 0018.
84 - Seeing if p0790 is from 0018.
85 - Seeing if p0791 is from 0018.
86 - Seeing if p0792 is from 0018.
87 - Seeing if p0793 is from 0018.
88 - Seeing if p0794 is from 0018.
89 - Seeing if p0870 is from 0018.
90 - Seeing if p0871 is from 0018.
91 - Seeing if p0872 is from 0018.
92 - Seeing if p0873 is from 0018.
93 - Seeing if p0874 is from 0018.
94 - Seeing if p0875 is from 0018.
95 - Seeing if p0876 is from 0018.
96 - Seeing if p0877 is from 0018.
97 - Seeing if p0878 is from 0018.
98 - Seeing if p0879 is from 0018.
99 - Seeing if p0880 is from 0018.
100 - Seeing if p0881 is from 0018.
101 - Seeing if p0882 is from 0018.
102 - Seeing if p0883 is from 0018.
103 - Seeing if p0884 is from 0018.
104 - Seeing if p0885 is from 0018.
105 - Seeing if p0892 is from 0018.
106 - Seeing if p0893 is from 0018.
107 - Seeing if p0894 is from 0018.
108 - Seeing if p0895 is from 0018.
109 - Seeing if p0896 is from 0018.
110 - Seeing if p0897 is from 0018.
111 - Seeing if p0898 is from 0018.
112 - Seeing if p0899 is from 0018.
113 - Seeing if p0900 is from 0018.
114 - Seeing if p0901 is from 0018.
115 - Seeing if p0902 is from 0018.
116 - Seeing if p0903 is from 0018.
117 - Seeing if p0904 is from 0018.
118 - Seeing if p0905 is from 0018.
119 - Seeing if p0906 is from 0018.
120 - Seeing if p0946 is from 0018.
121 - Seeing if p0947 is from 0018.
122 - Seeing if p0948 is from 0018.
123 - Seeing if p0966 is from 0018.
124 - Seeing if p0997 is from 0018.
125 - Seeing if p0998 is from 0018.
126 - Seeing if p0999 is from 0018.
127 - Seeing if p1000 is from 0018.
128 - Seeing if p1001 is from 0018.
129 - Seeing if p1002 is from 0018.
130 - Seeing if p1017 is from 0018.
131 - Seeing if p1018 is from 0018.
132 - Seeing if p1078 is from 0018.
133 - Seeing if p1137 is from 0018.
134 - Seeing if p1138 is from 0018.
135 - Seeing if p1139 is from 0018.
136 - Seeing if p1162 is from 0018.
137 - Seeing if p1172 is from 0018.
138 - Seeing if p1173 is from 0018.
139 - Seeing if p1174 is from 0018.
140 - Seeing if p1175 is from 0018.
141 - Seeing if p1192 is from 0018.
142 - Seeing if p1265 is from 0018.
143 - Seeing if p1266 is from 0018.
144 - Seeing if p1267 is from 0018.
145 - Seeing if p1268 is from 0018.
146 - Seeing if p1269 is from 0018.
147 - Seeing if p1270 is from 0018.
148 - Seeing if p1271 is from 0018.
149 - Seeing if p1272 is from 0018.
150 - Seeing if p1273 is from 0018.
151 - Seeing if p1274 is from 0018.
152 - Seeing if p1275 is from 0018.
153 - Seeing if p1276 is from 0018.
154 - Seeing if p1277 is from 0018.
155 - Seeing if p1278 is from 0018.
156 - Seeing if p1279 is from 0018.
157 - Seeing if p1280 is from 0018.
158 - Seeing if p1281 is from 0018.
159 - Seeing if p1282 is from 0018.
160 - Seeing if p1283 is from 0018.
161 - Seeing if p1284 is from 0018.
162 - Seeing if p1285 is from 0018.
163 - Seeing if p1286 is from 0018.
164 - Seeing if p1287 is from 0018.
165 - Seeing if p1324 is from 0018.
166 - Seeing if p1325 is from 0018.
167 - Seeing if p1326 is from 0018.
168 - Seeing if p1378 is from 0018.
169 - Seeing if p1379 is from 0018.
170 - Seeing if p1380 is from 0018.
171 - Seeing if p1381 is from 0018.
172 - Seeing if p1382 is from 0018.
173 - Seeing if p1383 is from 0018.
174 - Seeing if p1384 is from 0018.
175 - Seeing if p1385 is from 0018.
176 - Seeing if p1386 is from 0018.
177 - Seeing if p1387 is from 0018.
178 - Seeing if p1388 is from 0018.
179 - Seeing if p1453 is from 0018.
180 - Seeing if p1456 is from 0018.
181 - Seeing if p1457 is from 0018.
182 - Seeing if p1458 is from 0018.
183 - Seeing if p1459 is from 0018.
184 - Seeing if p1460 is from 0018.
185 - Seeing if p1461 is from 0018.
186 - Seeing if p1462 is from 0018.
187 - Seeing if p1463 is from 0018.
188 - Seeing if p1464 is from 0018.
189 - Seeing if p1465 is from 0018.
190 - Seeing if p1466 is from 0018.
191 - Seeing if p1469 is from 0018.
192 - Seeing if p1470 is from 0018.
193 - Seeing if p1471 is from 0018.
194 - Seeing if p1472 is from 0018.
195 - Seeing if p1473 is from 0018.
196 - Seeing if p1474 is from 0018.
197 - Seeing if p1475 is from 0018.
198 - Seeing if p1476 is from 0018.
199 - Seeing if p1477 is from 0018.
200 - Seeing if p1478 is from 0018.
201 - Seeing if p1502 is from 0018.
202 - Seeing if p1503 is from 0018.
203 - Seeing if p1504 is from 0018.
204 - Seeing if p1505 is from 0018.
205 - Seeing if p1506 is from 0018.
206 - Seeing if p1507 is from 0018.
207 - Seeing if p1508 is from 0018.
208 - Seeing if p1509 is from 0018.
209 - Seeing if p1510 is from 0018.
210 - Seeing if p1511 is from 0018.
211 - Seeing if p1512 is from 0018.
212 - Seeing if p1513 is from 0018.
213 - Seeing if p1562 is from 0018.
214 - Seeing if p1569 is from 0018.
215 - Seeing if p1570 is from 0018.
216 - Seeing if p1574 is from 0018.
217 - Seeing if p1575 is from 0018.
218 - Seeing if p1576 is from 0018.
219 - Seeing if p1577 is from 0018.
220 - Seeing if p1578 is from 0018.
221 - Seeing if p1597 is from 0018.
222 - Seeing if p1598 is from 0018.
223 - Seeing if p1599 is from 0018.
224 - Seeing if p1600 is from 0018.
225 - Seeing if p1601 is from 0018.
226 - Seeing if p1602 is from 0018.
227 - Seeing if p1603 is from 0018.
228 - Seeing if p1604 is from 0018.
229 - Seeing if p1605 is from 0018.
230 - Seeing if p1606 is from 0018.
231 - Seeing if p1607 is from 0018.
232 - Seeing if p1608 is from 0018.
233 - Seeing if p1609 is from 0018.
234 - Seeing if p1610 is from 0018.
235 - Seeing if p1611 is from 0018.
236 - Seeing if p1612 is from 0018.
237 - Seeing if p1687 is from 0018.
238 - Seeing if p1688 is from 0018.
239 - Seeing if p1689 is from 0018.
240 - Seeing if p1690 is from 0018.
241 - Seeing if p1691 is from 0018.
242 - Seeing if p1692 is from 0018.
243 - Seeing if p1693 is from 0018.
244 - Seeing if p1694 is from 0018.
245 - Seeing if p1695 is from 0018.
246 - Seeing if p1696 is from 0018.
247 - Seeing if p1697 is from 0018.
248 - Seeing if p1698 is from 0018.
249 - Seeing if p1699 is from 0018.
250 - Seeing if p1700 is from 0018.
251 - Seeing if p1701 is from 0018.
252 - Seeing if p1702 is from 0018.
253 - Seeing if p1703 is from 0018.
254 - Seeing if p1704 is from 0018.
255 - Seeing if p1718 is from 0018.
256 - Seeing if p1719 is from 0018.
257 - Seeing if p1720 is from 0018.
258 - Seeing if p1721 is from 0018.
259 - Seeing if p1722 is from 0018.
260 - Seeing if p1723 is from 0018.
261 - Seeing if p1724 is from 0018.
262 - Seeing if p1725 is from 0018.
263 - Seeing if p1726 is from 0018.
264 - Seeing if p1727 is from 0018.
265 - Seeing if p1728 is from 0018.
266 - Seeing if p1729 is from 0018.
267 - Seeing if p1730 is from 0018.
268 - Seeing if p1731 is from 0018.
269 - Seeing if p1732 is from 0018.
270 - Seeing if p1733 is from 0018.
271 - Seeing if p1734 is from 0018.
272 - Seeing if p1735 is from 0018.
273 - Seeing if p1736 is from 0018.
274 - Seeing if p1737 is from 0018.
275 - Seeing if p1738 is from 0018.
276 - Seeing if p1739 is from 0018.
277 - Seeing if p1815 is from 0018.
278 - Seeing if p1816 is from 0018.
279 - Seeing if p1817 is from 0018.
280 - Seeing if p1818 is from 0018.
281 - Seeing if p1819 is from 0018.
282 - Seeing if p1820 is from 0018.
283 - Seeing if p1821 is from 0018.
284 - Seeing if p1822 is from 0018.
285 - Seeing if p1823 is from 0018.
286 - Seeing if p1854 is from 0018.
287 - Seeing if p1855 is from 0018.
288 - Seeing if p1856 is from 0018.
289 - Seeing if p1857 is from 0018.
290 - Seeing if p1858 is from 0018.
291 - Seeing if p1859 is from 0018.
292 - Seeing if p1860 is from 0018.
293 - Seeing if p1861 is from 0018.
294 - Seeing if p1862 is from 0018.
295 - Seeing if p1863 is from 0018.
296 - Seeing if p1864 is from 0018.
297 - Seeing if p1865 is from 0018.
298 - Seeing if p1898 is from 0018.
299 - Seeing if p1899 is from 0018.
300 - Seeing if p1900 is from 0018.
301 - Seeing if p1901 is from 0018.
302 - Seeing if p1902 is from 0018.
303 - Seeing if p1903 is from 0018.
304 - Seeing if p1904 is from 0018.
305 - Seeing if p1905 is from 0018.
306 - Seeing if p1906 is from 0018.
307 - Seeing if p1907 is from 0018.
308 - Seeing if p1908 is from 0018.
309 - Seeing if p1909 is from 0018.
310 - Seeing if p1910 is from 0018.
311 - Seeing if p1911 is from 0018.
312 - Seeing if p1912 is from 0018.
313 - Seeing if p1913 is from 0018.
314 - Seeing if p1914 is from 0018.
315 - Seeing if p1915 is from 0018.
316 - Seeing if p1916 is from 0018.
317 - Seeing if p1917 is from 0018.
318 - Seeing if p1958 is from 0018.
319 - Seeing if p1975 is from 0018.
320 - Seeing if p1976 is from 0018.
321 - Seeing if p1977 is from 0018.
322 - Seeing if p1978 is from 0018.
323 - Seeing if p1979 is from 0018.
324 - Seeing if p1980 is from 0018.
325 - Seeing if p2084 is from 0018.
326 - Seeing if p2093 is from 0018.
327 - Seeing if p2094 is from 0018.
328 - Seeing if p2095 is from 0018.
329 - Seeing if p2096 is from 0018.
330 - Seeing if p2097 is from 0018.
331 - Seeing if p2098 is from 0018.
332 - Seeing if p2099 is from 0018.
333 - Seeing if p2100 is from 0018.
334 - Seeing if p2101 is from 0018.
335 - Seeing if p2102 is from 0018.
336 - Seeing if p2103 is from 0018.
337 - Seeing if p2104 is from 0018.
338 - Seeing if p2105 is from 0018.
339 - Seeing if p2106 is from 0018.
340 - Seeing if p2107 is from 0018.
341 - Seeing if p2108 is from 0018.
342 - Seeing if p2109 is from 0018.
343 - Seeing if p2110 is from 0018.
344 - Seeing if p2111 is from 0018.
345 - Seeing if p2112 is from 0018.
346 - Seeing if p2113 is from 0018.
347 - Seeing if p2114 is from 0018.
348 - Seeing if p2115 is from 0018.
349 - Seeing if p2116 is from 0018.
350 - Seeing if p2117 is from 0018.
351 - Seeing if p2129 is from 0018.
352 - Seeing if p2130 is from 0018.
353 - Seeing if p2131 is from 0018.
354 - Seeing if p2132 is from 0018.
355 - Seeing if p2133 is from 0018.
356 - Seeing if p2134 is from 0018.
357 - Seeing if p2135 is from 0018.
358 - Seeing if p2136 is from 0018.
359 - Seeing if p2137 is from 0018.
360 - Seeing if p2138 is from 0018.
361 - Seeing if p2139 is from 0018.
362 - Seeing if p2140 is from 0018.
363 - Seeing if p2141 is from 0018.
364 - Seeing if p2142 is from 0018.
365 - Seeing if p2143 is from 0018.
366 - Seeing if p2144 is from 0018.
367 - Seeing if p2145 is from 0018.
368 - Seeing if p2269 is from 0018.
369 - Seeing if p2270 is from 0018.
370 - Seeing if p2271 is from 0018.
371 - Seeing if p2272 is from 0018.
372 - Seeing if p2273 is from 0018.
373 - Seeing if p2274 is from 0018.
374 - Seeing if p2275 is from 0018.
375 - Seeing if p2276 is from 0018.
376 - Seeing if p2277 is from 0018.
377 - Seeing if p2278 is from 0018.
378 - Seeing if p2279 is from 0018.
379 - Seeing if p2280 is from 0018.
380 - Seeing if p2281 is from 0018.
381 - Seeing if p2282 is from 0018.
382 - Seeing if p2283 is from 0018.
383 - Seeing if p2284 is from 0018.
384 - Seeing if p2285 is from 0018.
385 - Seeing if p2286 is from 0018.
386 - Seeing if p2287 is from 0018.
387 - Seeing if p2288 is from 0018.
388 - Seeing if p2289 is from 0018.
389 - Seeing if p2290 is from 0018.
390 - Seeing if p2291 is from 0018.
391 - Seeing if p2304 is from 0018.
392 - Seeing if p2305 is from 0018.
393 - Seeing if p2306 is from 0018.
394 - Seeing if p2307 is from 0018.
395 - Seeing if p2308 is from 0018.
396 - Seeing if p2309 is from 0018.
397 - Seeing if p2310 is from 0018.
398 - Seeing if p2311 is from 0018.
399 - Seeing if p2312 is from 0018.
400 - Seeing if p2313 is from 0018.
401 - Seeing if p2314 is from 0018.
402 - Seeing if p2331 is from 0018.
403 - Seeing if p2425 is from 0018.
404 - Seeing if p2426 is from 0018.
405 - Seeing if p2427 is from 0018.
406 - Seeing if p2428 is from 0018.
407 - Seeing if p2429 is from 0018.
408 - Seeing if p2430 is from 0018.
409 - Seeing if p2431 is from 0018.
410 - Seeing if p2432 is from 0018.
411 - Seeing if p2433 is from 0018.
412 - Seeing if p2434 is from 0018.
413 - Seeing if p2435 is from 0018.
414 - Seeing if p2436 is from 0018.
415 - Seeing if p2437 is from 0018.
416 - Seeing if p2438 is from 0018.
417 - Seeing if p2439 is from 0018.
418 - Seeing if p2440 is from 0018.
419 - Seeing if p2441 is from 0018.
420 - Seeing if p2442 is from 0018.
421 - Seeing if p2500 is from 0018.
422 - Seeing if p2501 is from 0018.
423 - Seeing if p2502 is from 0018.
424 - Seeing if p2503 is from 0018.
425 - Seeing if p2504 is from 0018.
426 - Seeing if p2505 is from 0018.
427 - Seeing if p2506 is from 0018.
428 - Seeing if p2507 is from 0018.
429 - Seeing if p2508 is from 0018.
430 - Seeing if p2509 is from 0018.
431 - Seeing if p2510 is from 0018.
432 - Seeing if p2511 is from 0018.
433 - Seeing if p2512 is from 0018.
434 - Seeing if p2513 is from 0018.
435 - Seeing if p2514 is from 0018.
436 - Seeing if p2515 is from 0018.
437 - Seeing if p2516 is from 0018.
438 - Seeing if p2517 is from 0018.
439 - Seeing if p2518 is from 0018.
440 - Seeing if p2519 is from 0018.
441 - Seeing if p2520 is from 0018.
442 - Seeing if p2521 is from 0018.
443 - Seeing if p2522 is from 0018.
444 - Seeing if p2523 is from 0018.
445 - Seeing if p2524 is from 0018.
446 - Seeing if p2525 is from 0018.
447 - Seeing if p2526 is from 0018.
448 - Seeing if p2527 is from 0018.
449 - Seeing if p2528 is from 0018.
450 - Seeing if p2529 is from 0018.
451 - Seeing if p2530 is from 0018.
452 - Seeing if p2531 is from 0018.
453 - Seeing if p2532 is from 0018.
454 - Seeing if p2533 is from 0018.
455 - Seeing if p2534 is from 0018.
456 - Seeing if p2535 is from 0018.
457 - Seeing if p2536 is from 0018.
458 - Seeing if p2537 is from 0018.
459 - Seeing if p2538 is from 0018.
460 - Seeing if p2539 is from 0018.
461 - Seeing if p2540 is from 0018.
462 - Seeing if p2541 is from 0018.
463 - Seeing if p2542 is from 0018.
464 - Seeing if p2543 is from 0018.
465 - Seeing if p2544 is from 0018.
466 - Seeing if p2545 is from 0018.
467 - Seeing if p2546 is from 0018.
468 - Seeing if p2547 is from 0018.
469 - Seeing if p2548 is from 0018.
470 - Seeing if p2549 is from 0018.
471 - Seeing if p2550 is from 0018.
472 - Seeing if p2551 is from 0018.
473 - Seeing if p2552 is from 0018.
474 - Seeing if p2553 is from 0018.
475 - Seeing if p2554 is from 0018.
476 - Seeing if p2555 is from 0018.
477 - Seeing if p2556 is from 0018.
478 - Seeing if p2557 is from 0018.
479 - Seeing if p2651 is from 0018.
480 - Seeing if p2762 is from 0018.
481 - Seeing if p2763 is from 0018.
482 - Seeing if p2764 is from 0018.
483 - Seeing if p2765 is from 0018.
484 - Seeing if p2766 is from 0018.
485 - Seeing if p2767 is from 0018.
486 - Seeing if p2768 is from 0018.
487 - Seeing if p2769 is from 0018.
488 - Seeing if p2770 is from 0018.
489 - Seeing if p2771 is from 0018.
490 - Seeing if p2772 is from 0018.
491 - Seeing if p2773 is from 0018.
492 - Seeing if p2774 is from 0018.
493 - Seeing if p2775 is from 0018.
494 - Seeing if p2776 is from 0018.
495 - Seeing if p2777 is from 0018.
496 - Seeing if p2778 is from 0018.
497 - Seeing if p2779 is from 0018.
498 - Seeing if p2780 is from 0018.
499 - Seeing if p2781 is from 0018.
500 - Seeing if p2782 is from 0018.
501 - Seeing if p2783 is from 0018.
502 - Seeing if p2784 is from 0018.
503 - Seeing if p2832 is from 0018.
504 - Seeing if p2840 is from 0018.
505 - Seeing if p2842 is from 0018.
506 - Seeing if p2843 is from 0018.
507 - Seeing if p2844 is from 0018.
508 - Seeing if p2845 is from 0018.
509 - Seeing if p2846 is from 0018.
510 - Seeing if p2847 is from 0018.
511 - Seeing if p2848 is from 0018.
512 - Seeing if p2849 is from 0018.
513 - Seeing if p2871 is from 0018.
514 - Seeing if p2872 is from 0018.
515 - Seeing if p2888 is from 0018.
516 - Seeing if p2891 is from 0018.
517 - Seeing if p2899 is from 0018.
518 - Seeing if p2900 is from 0018.
519 - Seeing if p2901 is from 0018.
520 - Seeing if p2908 is from 0018.
521 - Seeing if p2916 is from 0018.
522 - Seeing if p2924 is from 0018.
523 - Seeing if p2928 is from 0018.
524 - Seeing if p2941 is from 0018.
525 - Seeing if p2942 is from 0018.
526 - Seeing if p2965 is from 0018.
527 - Seeing if p2966 is from 0018.
528 - Seeing if p2979 is from 0018.
529 - Seeing if p2980 is from 0018.
530 - Seeing if p2981 is from 0018.
531 - Seeing if p2994 is from 0018.
532 - Seeing if p2995 is from 0018.
533 - Seeing if p2998 is from 0018.
534 - Seeing if p2999 is from 0018.
535 - Seeing if p3005 is from 0018.
536 - Seeing if p3010 is from 0018.
537 - Seeing if p3011 is from 0018.
538 - Seeing if p3012 is from 0018.
539 - Seeing if p3016 is from 0018.
540 - Seeing if p3019 is from 0018.
541 - Seeing if p3020 is from 0018.
542 - Seeing if p3021 is from 0018.
543 - Seeing if p3030 is from 0018.
544 - Seeing if p3033 is from 0018.
545 - Seeing if p3037 is from 0018.
546 - Seeing if p3038 is from 0018.
547 - Seeing if p3063 is from 0018.
548 - Seeing if p3064 is from 0018.
549 - Seeing if p3065 is from 0018.
550 - Seeing if p3077 is from 0018.
551 - Seeing if p3079 is from 0018.
552 - Seeing if p3095 is from 0018.
553 - Seeing if p3096 is from 0018.
554 - Seeing if p3103 is from 0018.
555 - Seeing if p3104 is from 0018.
556 - Seeing if p3124 is from 0018.
557 - Seeing if p3125 is from 0018.

# Algoritmo 2

In [ ]:
all_missing_ids = pd.read_csv("all_missing_ids.csv")
all_missing_ids = all_missing_ids[all_missing_ids["origin"] == -1]

In [219]:
possible_origins = dict()

img_rgb_og = cv.imread(origin_paths[index])
img_og = cv.cvtColor(img_rgb_og, cv.IMREAD_GRAYSCALE)

for i, (p_img_name, p_img_path) in enumerate(zip(patches_name, patches_path)):
    img = img_og.copy()
    img_rgb = img_rgb_og.copy()

    p_img_rgb = cv.imread(p_img_path)
    p_img = cv.cvtColor(p_img_rgb, cv.IMREAD_GRAYSCALE)
    pw, ph = p_img.shape[:-1]

    for img_name, img_part in zip(origin_list, origin_paths):
        img_rgb = cv.imread(img_part)
        img = cv.cvtColor(img_rgb, cv.IMREAD_GRAYSCALE)

        print(f"{i} - Seeing if {p_img_name} is from {img_name}.")

        method = cv.TM_CCOEFF_NORMED

        res = cv.matchTemplate(img_rgb, p_img_rgb, method)
        min_val, max_val, min_loc, max_loc = cv.minMaxLoc(res)
                
        # loc = np.where(res > 0.4)
                
        # if not len(loc[0]) and not len(loc[1]):
        #     continue
                
        top_left = max_loc
        bottom_right = (top_left[0] + pw, top_left[1] + ph)   
                
        cv.rectangle(img_rgb, top_left, bottom_right, 123, 6)

        plt.subplot(1, 2, 1), plt.imshow(p_img_rgb)
        plt.title(f'Patch Point {p_img_name}'), plt.xticks([]), plt.yticks([])
        plt.subplot(1, 2, 2), plt.imshow(img_rgb)
        plt.title(f'Detected point {img_name}'), plt.xticks([]), plt.yticks([])
        plt.savefig(LINK_PATH / f"temp/patch_{p_img_name}_origin_{img_name}.png")

        plt.close()

0 - Seeing if p0010 is from 0000.
0 - Seeing if p0010 is from 0001.
0 - Seeing if p0010 is from 0002.
0 - Seeing if p0010 is from 0003.
0 - Seeing if p0010 is from 0004.
0 - Seeing if p0010 is from 0005.
0 - Seeing if p0010 is from 0006.
0 - Seeing if p0010 is from 0007.
0 - Seeing if p0010 is from 0008.
0 - Seeing if p0010 is from 0009.
0 - Seeing if p0010 is from 0010.
0 - Seeing if p0010 is from 0011.
0 - Seeing if p0010 is from 0012.
0 - Seeing if p0010 is from 0013.
0 - Seeing if p0010 is from 0014.
0 - Seeing if p0010 is from 0015.
0 - Seeing if p0010 is from 0016.
0 - Seeing if p0010 is from 0017.
0 - Seeing if p0010 is from 0018.
0 - Seeing if p0010 is from 0019.
0 - Seeing if p0010 is from 0020.
0 - Seeing if p0010 is from 0021.
0 - Seeing if p0010 is from 0022.
0 - Seeing if p0010 is from 0023.
0 - Seeing if p0010 is from 0024.
0 - Seeing if p0010 is from 0025.
0 - Seeing if p0010 is from 0026.
0 - Seeing if p0010 is from 0027.
0 - Seeing if p0010 is from 0028.
0 - Seeing if p0010 is from 0029.
0 - Seeing if p0010 is from 0030.
0 - Seeing if p0010 is from 0031.
0 - Seeing if p0010 is from 0032.
0 - Seeing if p0010 is from 0033.
0 - Seeing if p0010 is from 0034.
0 - Seeing if p0010 is from 0035.
0 - Seeing if p0010 is from 0036.
0 - Seeing if p0010 is from 0037.
0 - Seeing if p0010 is from 0038.
0 - Seeing if p0010 is from 0039.
0 - Seeing if p0010 is from 0040.
0 - Seeing if p0010 is from 0041.
0 - Seeing if p0010 is from 0042.
0 - Seeing if p0010 is from 0043.
0 - Seeing if p0010 is from 0044.
0 - Seeing if p0010 is from 0045.
0 - Seeing if p0010 is from 0046.
0 - Seeing if p0010 is from 0047.
0 - Seeing if p0010 is from 0048.
0 - Seeing if p0010 is from 0049.
0 - Seeing if p0010 is from 0050.
0 - Seeing if p0010 is from 0051.
0 - Seeing if p0010 is from 0052.
0 - Seeing if p0010 is from 0053.
0 - Seeing if p0010 is from 0054.
0 - Seeing if p0010 is from 0055.
0 - Seeing if p0010 is from 0056.
0 - Seeing if p0010 is from 0057.
0 - Seeing if p0010 is from 0058.
0 - Seeing if p0010 is from 0059.
0 - Seeing if p0010 is from 0060.
0 - Seeing if p0010 is from 0061.
0 - Seeing if p0010 is from 0062.
0 - Seeing if p0010 is from 0063.
0 - Seeing if p0010 is from 0064.
0 - Seeing if p0010 is from 0065.
0 - Seeing if p0010 is from 0066.
0 - Seeing if p0010 is from 0067.
0 - Seeing if p0010 is from 0068.
0 - Seeing if p0010 is from 0069.
0 - Seeing if p0010 is from 0070.
0 - Seeing if p0010 is from 0071.
0 - Seeing if p0010 is from 0072.
0 - Seeing if p0010 is from 0073.
0 - Seeing if p0010 is from 0074.
0 - Seeing if p0010 is from 0075.
0 - Seeing if p0010 is from 0076.
0 - Seeing if p0010 is from 0077.
0 - Seeing if p0010 is from 0078.
0 - Seeing if p0010 is from 0079.
0 - Seeing if p0010 is from 0080.
0 - Seeing if p0010 is from 0081.
0 - Seeing if p0010 is from 0082.
0 - Seeing if p0010 is from 0083.
0 - Seeing if p0010 is from 0084.
0 - Seeing if p0010 is from 0085.
0 - Seeing if p0010 is from 0086.
0 - Seeing if p0010 is from 0087.
0 - Seeing if p0010 is from 0088.
0 - Seeing if p0010 is from 0089.
0 - Seeing if p0010 is from 0090.
0 - Seeing if p0010 is from 0091.
0 - Seeing if p0010 is from 0092.
0 - Seeing if p0010 is from 0093.
0 - Seeing if p0010 is from 0094.
0 - Seeing if p0010 is from 0095.
0 - Seeing if p0010 is from 0096.
0 - Seeing if p0010 is from 0097.
0 - Seeing if p0010 is from 0098.
0 - Seeing if p0010 is from 0099.
0 - Seeing if p0010 is from 0100.
0 - Seeing if p0010 is from 0101.
0 - Seeing if p0010 is from 0102.
0 - Seeing if p0010 is from 0103.
0 - Seeing if p0010 is from 0104.
0 - Seeing if p0010 is from 0105.
0 - Seeing if p0010 is from 0106.
0 - Seeing if p0010 is from 0107.
0 - Seeing if p0010 is from 0108.
0 - Seeing if p0010 is from 0109.
0 - Seeing if p0010 is from 0110.
0 - Seeing if p0010 is from 0111.
0 - Seeing if p0010 is from 0112.
0 - Seeing if p0010 is from 0113.
0 - Seeing if p0010 is from 0114.
0 - Seeing if p0010 is from 0115.
0 - Seeing if p0010 is from 0116.
0 - Seeing if p0010 is from 0117.
0 - Seeing if p0010 is from 0118.
0 - Seeing if p0010 is from 0119.
0 - Seeing if p0010 is from 0120.
0 - Seeing if p0010 is from 0121.
0 - Seeing if p0010 is from 0122.
0 - Seeing if p0010 is from 0123.
0 - Seeing if p0010 is from 0124.
0 - Seeing if p0010 is from 0125.
0 - Seeing if p0010 is from 0126.
0 - Seeing if p0010 is from 0127.
0 - Seeing if p0010 is from 0128.
0 - Seeing if p0010 is from 0129.
0 - Seeing if p0010 is from 0130.
0 - Seeing if p0010 is from 0131.
0 - Seeing if p0010 is from 0132.
0 - Seeing if p0010 is from 0133.
0 - Seeing if p0010 is from 0134.
0 - Seeing if p0010 is from 0135.
0 - Seeing if p0010 is from 0136.
0 - Seeing if p0010 is from 0137.
0 - Seeing if p0010 is from 0138.
0 - Seeing if p0010 is from 0139.
0 - Seeing if p0010 is from 0140.
0 - Seeing if p0010 is from 0141.
0 - Seeing if p0010 is from 0142.
0 - Seeing if p0010 is from 0143.
0 - Seeing if p0010 is from 0144.
0 - Seeing if p0010 is from 0145.
0 - Seeing if p0010 is from 0146.
0 - Seeing if p0010 is from 0147.
0 - Seeing if p0010 is from 0148.
0 - Seeing if p0010 is from 0149.
0 - Seeing if p0010 is from 0150.
0 - Seeing if p0010 is from 0151.
0 - Seeing if p0010 is from 0152.
0 - Seeing if p0010 is from 0153.
0 - Seeing if p0010 is from 0154.
0 - Seeing if p0010 is from 0155.
0 - Seeing if p0010 is from 0156.
0 - Seeing if p0010 is from 0157.
0 - Seeing if p0010 is from 0158.
0 - Seeing if p0010 is from 0159.
0 - Seeing if p0010 is from 0160.
0 - Seeing if p0010 is from 0161.
0 - Seeing if p0010 is from 0162.
0 - Seeing if p0010 is from 0163.
0 - Seeing if p0010 is from 0164.
0 - Seeing if p0010 is from 0165.
0 - Seeing if p0010 is from 0166.
0 - Seeing if p0010 is from 0167.
0 - Seeing if p0010 is from 0168.
0 - Seeing if p0010 is from 0169.
0 - Seeing if p0010 is from 0170.
0 - Seeing if p0010 is from 0171.
0 - Seeing if p0010 is from 0172.
0 - Seeing if p0010 is from 0173.
0 - Seeing if p0010 is from 0174.
0 - Seeing if p0010 is from 0175.
0 - Seeing if p0010 is from 0176.
0 - Seeing if p0010 is from 0177.
0 - Seeing if p0010 is from 0178.
0 - Seeing if p0010 is from 0179.
0 - Seeing if p0010 is from 0180.
0 - Seeing if p0010 is from 0181.
0 - Seeing if p0010 is from 0182.
0 - Seeing if p0010 is from 0183.
0 - Seeing if p0010 is from 0184.
0 - Seeing if p0010 is from 0185.
0 - Seeing if p0010 is from 0186.
0 - Seeing if p0010 is from 0187.
0 - Seeing if p0010 is from 0188.
0 - Seeing if p0010 is from 0189.
0 - Seeing if p0010 is from 0190.
0 - Seeing if p0010 is from 0191.
0 - Seeing if p0010 is from 0192.
0 - Seeing if p0010 is from 0193.
0 - Seeing if p0010 is from 0194.
0 - Seeing if p0010 is from 0195.
0 - Seeing if p0010 is from 0196.
0 - Seeing if p0010 is from 0197.
0 - Seeing if p0010 is from 0198.
0 - Seeing if p0010 is from 0199.
0 - Seeing if p0010 is from 0200.
0 - Seeing if p0010 is from 0201.
0 - Seeing if p0010 is from 0202.
0 - Seeing if p0010 is from 0203.
0 - Seeing if p0010 is from 0204.
0 - Seeing if p0010 is from 0205.
0 - Seeing if p0010 is from 0206.
0 - Seeing if p0010 is from 0207.
0 - Seeing if p0010 is from 0208.
0 - Seeing if p0010 is from 0209.
0 - Seeing if p0010 is from 0210.
0 - Seeing if p0010 is from 0211.
0 - Seeing if p0010 is from 0212.
0 - Seeing if p0010 is from 0213.
0 - Seeing if p0010 is from 0214.
0 - Seeing if p0010 is from 0215.
0 - Seeing if p0010 is from 0216.
0 - Seeing if p0010 is from 0217.
0 - Seeing if p0010 is from 0218.
0 - Seeing if p0010 is from 0219.
0 - Seeing if p0010 is from 0220.
0 - Seeing if p0010 is from 0221.
0 - Seeing if p0010 is from 0222.
0 - Seeing if p0010 is from 0223.
0 - Seeing if p0010 is from 0224.
0 - Seeing if p0010 is from 0225.
0 - Seeing if p0010 is from 0226.
0 - Seeing if p0010 is from 0227.
0 - Seeing if p0010 is from 0228.
0 - Seeing if p0010 is from 0229.
0 - Seeing if p0010 is from 0230.
0 - Seeing if p0010 is from 0231.
0 - Seeing if p0010 is from 0232.
0 - Seeing if p0010 is from 0233.
0 - Seeing if p0010 is from 0234.
0 - Seeing if p0010 is from 0235.
0 - Seeing if p0010 is from 0236.
1 - Seeing if p0011 is from 0000.
1 - Seeing if p0011 is from 0001.
1 - Seeing if p0011 is from 0002.
1 - Seeing if p0011 is from 0003.
1 - Seeing if p0011 is from 0004.
1 - Seeing if p0011 is from 0005.
1 - Seeing if p0011 is from 0006.
1 - Seeing if p0011 is from 0007.
1 - Seeing if p0011 is from 0008.
1 - Seeing if p0011 is from 0009.
1 - Seeing if p0011 is from 0010.
1 - Seeing if p0011 is from 0011.
1 - Seeing if p0011 is from 0012.
1 - Seeing if p0011 is from 0013.
1 - Seeing if p0011 is from 0014.
1 - Seeing if p0011 is from 0015.
1 - Seeing if p0011 is from 0016.
1 - Seeing if p0011 is from 0017.
1 - Seeing if p0011 is from 0018.
1 - Seeing if p0011 is from 0019.
1 - Seeing if p0011 is from 0020.
1 - Seeing if p0011 is from 0021.
1 - Seeing if p0011 is from 0022.
1 - Seeing if p0011 is from 0023.
1 - Seeing if p0011 is from 0024.
1 - Seeing if p0011 is from 0025.
1 - Seeing if p0011 is from 0026.
1 - Seeing if p0011 is from 0027.
1 - Seeing if p0011 is from 0028.
1 - Seeing if p0011 is from 0029.
1 - Seeing if p0011 is from 0030.
1 - Seeing if p0011 is from 0031.
1 - Seeing if p0011 is from 0032.
1 - Seeing if p0011 is from 0033.
1 - Seeing if p0011 is from 0034.
1 - Seeing if p0011 is from 0035.
1 - Seeing if p0011 is from 0036.
1 - Seeing if p0011 is from 0037.
1 - Seeing if p0011 is from 0038.
1 - Seeing if p0011 is from 0039.
1 - Seeing if p0011 is from 0040.
1 - Seeing if p0011 is from 0041.
1 - Seeing if p0011 is from 0042.
1 - Seeing if p0011 is from 0043.
1 - Seeing if p0011 is from 0044.
1 - Seeing if p0011 is from 0045.
1 - Seeing if p0011 is from 0046.
1 - Seeing if p0011 is from 0047.
1 - Seeing if p0011 is from 0048.
1 - Seeing if p0011 is from 0049.
1 - Seeing if p0011 is from 0050.
1 - Seeing if p0011 is from 0051.
1 - Seeing if p0011 is from 0052.
1 - Seeing if p0011 is from 0053.
1 - Seeing if p0011 is from 0054.
1 - Seeing if p0011 is from 0055.
1 - Seeing if p0011 is from 0056.
1 - Seeing if p0011 is from 0057.
1 - Seeing if p0011 is from 0058.
1 - Seeing if p0011 is from 0059.
1 - Seeing if p0011 is from 0060.
1 - Seeing if p0011 is from 0061.
1 - Seeing if p0011 is from 0062.
1 - Seeing if p0011 is from 0063.
1 - Seeing if p0011 is from 0064.
1 - Seeing if p0011 is from 0065.
1 - Seeing if p0011 is from 0066.
1 - Seeing if p0011 is from 0067.
1 - Seeing if p0011 is from 0068.
1 - Seeing if p0011 is from 0069.
1 - Seeing if p0011 is from 0070.
1 - Seeing if p0011 is from 0071.
1 - Seeing if p0011 is from 0072.
1 - Seeing if p0011 is from 0073.
1 - Seeing if p0011 is from 0074.
1 - Seeing if p0011 is from 0075.
1 - Seeing if p0011 is from 0076.
1 - Seeing if p0011 is from 0077.
1 - Seeing if p0011 is from 0078.
1 - Seeing if p0011 is from 0079.
1 - Seeing if p0011 is from 0080.
1 - Seeing if p0011 is from 0081.
1 - Seeing if p0011 is from 0082.
1 - Seeing if p0011 is from 0083.
1 - Seeing if p0011 is from 0084.
1 - Seeing if p0011 is from 0085.
1 - Seeing if p0011 is from 0086.
1 - Seeing if p0011 is from 0087.
1 - Seeing if p0011 is from 0088.
1 - Seeing if p0011 is from 0089.
1 - Seeing if p0011 is from 0090.
1 - Seeing if p0011 is from 0091.
1 - Seeing if p0011 is from 0092.
1 - Seeing if p0011 is from 0093.
1 - Seeing if p0011 is from 0094.
1 - Seeing if p0011 is from 0095.
1 - Seeing if p0011 is from 0096.
1 - Seeing if p0011 is from 0097.
1 - Seeing if p0011 is from 0098.
1 - Seeing if p0011 is from 0099.
1 - Seeing if p0011 is from 0100.
1 - Seeing if p0011 is from 0101.
1 - Seeing if p0011 is from 0102.
1 - Seeing if p0011 is from 0103.
1 - Seeing if p0011 is from 0104.
1 - Seeing if p0011 is from 0105.
1 - Seeing if p0011 is from 0106.
1 - Seeing if p0011 is from 0107.
1 - Seeing if p0011 is from 0108.
1 - Seeing if p0011 is from 0109.
1 - Seeing if p0011 is from 0110.
1 - Seeing if p0011 is from 0111.
1 - Seeing if p0011 is from 0112.
1 - Seeing if p0011 is from 0113.
1 - Seeing if p0011 is from 0114.
1 - Seeing if p0011 is from 0115.
1 - Seeing if p0011 is from 0116.
1 - Seeing if p0011 is from 0117.
1 - Seeing if p0011 is from 0118.
1 - Seeing if p0011 is from 0119.
1 - Seeing if p0011 is from 0120.
1 - Seeing if p0011 is from 0121.
1 - Seeing if p0011 is from 0122.
1 - Seeing if p0011 is from 0123.
1 - Seeing if p0011 is from 0124.
1 - Seeing if p0011 is from 0125.
1 - Seeing if p0011 is from 0126.
1 - Seeing if p0011 is from 0127.
1 - Seeing if p0011 is from 0128.
1 - Seeing if p0011 is from 0129.
1 - Seeing if p0011 is from 0130.
1 - Seeing if p0011 is from 0131.
1 - Seeing if p0011 is from 0132.
1 - Seeing if p0011 is from 0133.
1 - Seeing if p0011 is from 0134.
1 - Seeing if p0011 is from 0135.
1 - Seeing if p0011 is from 0136.
1 - Seeing if p0011 is from 0137.
1 - Seeing if p0011 is from 0138.
1 - Seeing if p0011 is from 0139.
1 - Seeing if p0011 is from 0140.
1 - Seeing if p0011 is from 0141.
1 - Seeing if p0011 is from 0142.
1 - Seeing if p0011 is from 0143.
1 - Seeing if p0011 is from 0144.
1 - Seeing if p0011 is from 0145.
1 - Seeing if p0011 is from 0146.
1 - Seeing if p0011 is from 0147.
1 - Seeing if p0011 is from 0148.
1 - Seeing if p0011 is from 0149.
1 - Seeing if p0011 is from 0150.
1 - Seeing if p0011 is from 0151.
1 - Seeing if p0011 is from 0152.
1 - Seeing if p0011 is from 0153.
1 - Seeing if p0011 is from 0154.
1 - Seeing if p0011 is from 0155.
1 - Seeing if p0011 is from 0156.
1 - Seeing if p0011 is from 0157.
1 - Seeing if p0011 is from 0158.
1 - Seeing if p0011 is from 0159.
1 - Seeing if p0011 is from 0160.
1 - Seeing if p0011 is from 0161.
1 - Seeing if p0011 is from 0162.
1 - Seeing if p0011 is from 0163.
1 - Seeing if p0011 is from 0164.
1 - Seeing if p0011 is from 0165.
1 - Seeing if p0011 is from 0166.
1 - Seeing if p0011 is from 0167.
1 - Seeing if p0011 is from 0168.
1 - Seeing if p0011 is from 0169.
1 - Seeing if p0011 is from 0170.
1 - Seeing if p0011 is from 0171.
1 - Seeing if p0011 is from 0172.
1 - Seeing if p0011 is from 0173.
1 - Seeing if p0011 is from 0174.
1 - Seeing if p0011 is from 0175.
1 - Seeing if p0011 is from 0176.
1 - Seeing if p0011 is from 0177.
1 - Seeing if p0011 is from 0178.
1 - Seeing if p0011 is from 0179.
1 - Seeing if p0011 is from 0180.
1 - Seeing if p0011 is from 0181.
1 - Seeing if p0011 is from 0182.
1 - Seeing if p0011 is from 0183.
1 - Seeing if p0011 is from 0184.
1 - Seeing if p0011 is from 0185.
1 - Seeing if p0011 is from 0186.
1 - Seeing if p0011 is from 0187.
1 - Seeing if p0011 is from 0188.
1 - Seeing if p0011 is from 0189.
1 - Seeing if p0011 is from 0190.
1 - Seeing if p0011 is from 0191.
1 - Seeing if p0011 is from 0192.
1 - Seeing if p0011 is from 0193.
1 - Seeing if p0011 is from 0194.
1 - Seeing if p0011 is from 0195.
1 - Seeing if p0011 is from 0196.
1 - Seeing if p0011 is from 0197.
1 - Seeing if p0011 is from 0198.
1 - Seeing if p0011 is from 0199.
1 - Seeing if p0011 is from 0200.
1 - Seeing if p0011 is from 0201.
1 - Seeing if p0011 is from 0202.
1 - Seeing if p0011 is from 0203.
1 - Seeing if p0011 is from 0204.
1 - Seeing if p0011 is from 0205.
1 - Seeing if p0011 is from 0206.
1 - Seeing if p0011 is from 0207.
1 - Seeing if p0011 is from 0208.
1 - Seeing if p0011 is from 0209.
1 - Seeing if p0011 is from 0210.
1 - Seeing if p0011 is from 0211.
1 - Seeing if p0011 is from 0212.
1 - Seeing if p0011 is from 0213.
1 - Seeing if p0011 is from 0214.
1 - Seeing if p0011 is from 0215.
1 - Seeing if p0011 is from 0216.
1 - Seeing if p0011 is from 0217.
1 - Seeing if p0011 is from 0218.
1 - Seeing if p0011 is from 0219.
1 - Seeing if p0011 is from 0220.
1 - Seeing if p0011 is from 0221.
1 - Seeing if p0011 is from 0222.
1 - Seeing if p0011 is from 0223.
1 - Seeing if p0011 is from 0224.
1 - Seeing if p0011 is from 0225.
1 - Seeing if p0011 is from 0226.
1 - Seeing if p0011 is from 0227.
1 - Seeing if p0011 is from 0228.
1 - Seeing if p0011 is from 0229.
1 - Seeing if p0011 is from 0230.
1 - Seeing if p0011 is from 0231.
1 - Seeing if p0011 is from 0232.
1 - Seeing if p0011 is from 0233.
1 - Seeing if p0011 is from 0234.
1 - Seeing if p0011 is from 0235.
1 - Seeing if p0011 is from 0236.
2 - Seeing if p0012 is from 0000.
2 - Seeing if p0012 is from 0001.
2 - Seeing if p0012 is from 0002.
2 - Seeing if p0012 is from 0003.
2 - Seeing if p0012 is from 0004.
2 - Seeing if p0012 is from 0005.
2 - Seeing if p0012 is from 0006.
2 - Seeing if p0012 is from 0007.
2 - Seeing if p0012 is from 0008.
2 - Seeing if p0012 is from 0009.
2 - Seeing if p0012 is from 0010.
2 - Seeing if p0012 is from 0011.
2 - Seeing if p0012 is from 0012.
2 - Seeing if p0012 is from 0013.
2 - Seeing if p0012 is from 0014.
2 - Seeing if p0012 is from 0015.
2 - Seeing if p0012 is from 0016.
2 - Seeing if p0012 is from 0017.
2 - Seeing if p0012 is from 0018.
2 - Seeing if p0012 is from 0019.
2 - Seeing if p0012 is from 0020.
2 - Seeing if p0012 is from 0021.
2 - Seeing if p0012 is from 0022.
2 - Seeing if p0012 is from 0023.
2 - Seeing if p0012 is from 0024.
2 - Seeing if p0012 is from 0025.
2 - Seeing if p0012 is from 0026.
2 - Seeing if p0012 is from 0027.
2 - Seeing if p0012 is from 0028.
2 - Seeing if p0012 is from 0029.
2 - Seeing if p0012 is from 0030.
2 - Seeing if p0012 is from 0031.
2 - Seeing if p0012 is from 0032.
2 - Seeing if p0012 is from 0033.
2 - Seeing if p0012 is from 0034.
2 - Seeing if p0012 is from 0035.
2 - Seeing if p0012 is from 0036.
2 - Seeing if p0012 is from 0037.
2 - Seeing if p0012 is from 0038.
2 - Seeing if p0012 is from 0039.
2 - Seeing if p0012 is from 0040.
2 - Seeing if p0012 is from 0041.
2 - Seeing if p0012 is from 0042.
2 - Seeing if p0012 is from 0043.
2 - Seeing if p0012 is from 0044.
2 - Seeing if p0012 is from 0045.
2 - Seeing if p0012 is from 0046.
2 - Seeing if p0012 is from 0047.
2 - Seeing if p0012 is from 0048.
2 - Seeing if p0012 is from 0049.
2 - Seeing if p0012 is from 0050.
2 - Seeing if p0012 is from 0051.
2 - Seeing if p0012 is from 0052.
2 - Seeing if p0012 is from 0053.
2 - Seeing if p0012 is from 0054.
2 - Seeing if p0012 is from 0055.
2 - Seeing if p0012 is from 0056.
2 - Seeing if p0012 is from 0057.
2 - Seeing if p0012 is from 0058.
2 - Seeing if p0012 is from 0059.
2 - Seeing if p0012 is from 0060.
2 - Seeing if p0012 is from 0061.
2 - Seeing if p0012 is from 0062.
2 - Seeing if p0012 is from 0063.
2 - Seeing if p0012 is from 0064.
2 - Seeing if p0012 is from 0065.
2 - Seeing if p0012 is from 0066.
2 - Seeing if p0012 is from 0067.
2 - Seeing if p0012 is from 0068.
2 - Seeing if p0012 is from 0069.
2 - Seeing if p0012 is from 0070.
2 - Seeing if p0012 is from 0071.
2 - Seeing if p0012 is from 0072.
2 - Seeing if p0012 is from 0073.
2 - Seeing if p0012 is from 0074.
2 - Seeing if p0012 is from 0075.
2 - Seeing if p0012 is from 0076.
2 - Seeing if p0012 is from 0077.
2 - Seeing if p0012 is from 0078.
2 - Seeing if p0012 is from 0079.
2 - Seeing if p0012 is from 0080.
2 - Seeing if p0012 is from 0081.
2 - Seeing if p0012 is from 0082.
2 - Seeing if p0012 is from 0083.
2 - Seeing if p0012 is from 0084.
2 - Seeing if p0012 is from 0085.
2 - Seeing if p0012 is from 0086.
2 - Seeing if p0012 is from 0087.
2 - Seeing if p0012 is from 0088.
2 - Seeing if p0012 is from 0089.
2 - Seeing if p0012 is from 0090.
2 - Seeing if p0012 is from 0091.
2 - Seeing if p0012 is from 0092.
2 - Seeing if p0012 is from 0093.
2 - Seeing if p0012 is from 0094.
2 - Seeing if p0012 is from 0095.
2 - Seeing if p0012 is from 0096.
2 - Seeing if p0012 is from 0097.
2 - Seeing if p0012 is from 0098.
2 - Seeing if p0012 is from 0099.
2 - Seeing if p0012 is from 0100.
2 - Seeing if p0012 is from 0101.
2 - Seeing if p0012 is from 0102.
2 - Seeing if p0012 is from 0103.
2 - Seeing if p0012 is from 0104.
2 - Seeing if p0012 is from 0105.
2 - Seeing if p0012 is from 0106.
2 - Seeing if p0012 is from 0107.
2 - Seeing if p0012 is from 0108.
2 - Seeing if p0012 is from 0109.
2 - Seeing if p0012 is from 0110.
2 - Seeing if p0012 is from 0111.
2 - Seeing if p0012 is from 0112.
2 - Seeing if p0012 is from 0113.

: